# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c5f7d7de9517165409294cd46d597c8a5b118fa5392ea84e718cf2265e1c7c64843e748801d215bae753879b1d8926cd9d8c7dfabf5d0bf19cdc4cf880997a

test:
  secret_key_base: e65b2e00c832c8564d58742e85c093ea98ed76203a688340f1a4812788714922843693722ea497f98de924ed4bcbe9de152369adb12c92d307b4355524260e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
